#!/bin/bash
ip=`cat /etc/VpsPackdir/ip`;
function borrarusuarios(){
rm /etc/VpsPackdir/users
awk -F : '$3 > 900 { print $1 }' /etc/passwd | grep -v "nobody" |grep -vi polkitd |grep -vi system- | sort -d | nl >> /etc/VpsPackdir/users
cat /etc/VpsPackdir/users | sort -d
 read -p "Selecciona un numero: " name
 rm /etc/VpsPackdir/eliminado
 grep -w $name /etc/VpsPackdir/users |  awk '{print $2; }' >> /etc/VpsPackdir/eliminado
 eliminado=$(cat /etc/VpsPackdir/eliminado)
 sed -i "/$eliminado/d" /root/usuarios.db
 killall -u $eliminado
 userdel --force $eliminado
  #if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 #echo "Usuario no existe"
 echo -e "\033[1;37mUsuario \033[1;32m $eliminado \033[1;37meliminado\033[0m"
 vpspack 2
 }
clear
if [[ $1 == "" ]]
then
figlet -p -f slant < /root/name
echo -e "\033[1;37m      【     ★ VPSPack v. $vpspackversion ★     】\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;32m ───────────────── /// ─────────────────\033[1;33m"
echo -e "\033[1;37m › Linux Dist:	$distribution › Version: $os_version\033[0m"
echo -e "\033[1;37m › IP VPS:       $ip \033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;32m ───────────────── /// ─────────────────\033[1;33m"
echo -e "\033[1;37m       VPSPack $vpspackversion @ ELIMINAR USUARIO \033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m Eliminar usuario de la base de datos\033[1;33m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m ───────────────── /// ─────────────────\033[1;33m"
echo -e "\033[1;37mSeleccione una opcion:    Para Salir Ctrl + C\033[1;33m
[\033[1;32m1\033[1;33m] ELIMINAR USUARIO \033[1;33m
[\033[1;32m0\033[1;33m] < REGRESAR \033[1;33m"
read -p ": " opcao
else
opcao=$1
fi
case $opcao in
  1) 
  borrarusuarios;;
  0)
  vpspack;;
    esac
	