#!/bin/bash
fecha=`date`;
IP=$(curl -4 icanhazip.com)
clear && printf '\e[3J'
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mESPERE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31mΔ"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mESPERE\033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
if [ $(id -u) != 0 ]
then
echo "Ejecute el script como root"
exit
fi
clear
echo -e "Iniciando..."
cd /root
rm /root/name &>/dev/null
mkdir /etc/VpsPackdir  2>/dev/null
mkdir /etc/VpsPackdir/v7 2>/dev/null
apt-get install curl -y 1> /dev/null 2> /dev/null
apt-get install zip -y 1> /dev/null 2> /dev/null
apt-get install python2 -y 1> /dev/null 2> /dev/null
apt-get install toilet -y 1> /dev/null 2> /dev/null
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output /etc/VpsPackdir/get-pip.py 1> /dev/null 2> /dev/null
python2 /etc/VpsPackdir/get-pip.py 1> /dev/null 2> /dev/null
clear
echo -e "\033[1;32m "
echo -e "[\033[1;31m-\033[1;33m]\033[1;33m ───────────────────────────────────────\033[1;33m"
echo -e "\033[1;33mInstalando \033[1;32mProminex\033[0m"
echo -e "\033[1;33mIP del Servidor: \033[1;32m $IP \033[0m"
echo -e "\033[1;33mGrupo de Telegram: \033[1;32m@Pendiente\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;33m ───────────────────────────────────────\033[1;33m"
sleep 5
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m Preparando Sistema\033[1;33m"
function preparar(){
touch /root/usuarios.db
touch /root/badvpn.log
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null
mkdir /etc/VpsPackdir/v 2>/dev/null
mkdir /etc/VpsPackdir/socks 2>/dev/null
rm /etc/VpsPackdir/fecha 2>/dev/null
rm /bin/limite 2>/dev/null
curl -o /bin/limite https://raw.githubusercontent.com/devpow23/sc/main/files/limite 1> /dev/null 2> /dev/null
chmod +x /bin/limite
rm -rf /etc/VpsPackdir/sshconf 2>/dev/null
curl -o /etc/VpsPackdir/sshconf https://raw.githubusercontent.com/devpow23/sc/main/files/sshconf 1> /dev/null 2> /dev/null
rm -rf /bin/criarusuario
curl -o /bin/criarusuario https://raw.githubusercontent.com/devpow23/sc/main/files/criarusuario 1> /dev/null 2> /dev/null
chmod +x /bin/criarusuario
rm -rf /bin/criarusuariotoken
curl -o /bin/criarusuariotoken https://raw.githubusercontent.com/devpow23/sc/main/files/criarusuariotoken 1> /dev/null 2> /dev/null
chmod +x /bin/criarusuariotoken
rm -rf /bin/deletarusuario
curl -o /bin/deletarusuario https://raw.githubusercontent.com/devpow23/sc/main/files/deletarusuario 1> /dev/null 2> /dev/null
chmod +x /bin/deletarusuario
rm -rf /bin/redefinirusuario
curl -o /bin/redefinirusuario https://raw.githubusercontent.com/devpow23/sc/main/files/redefinirusuario 1> /dev/null 2> /dev/null
chmod +x /bin/redefinirusuario
rm -rf /bin/renovarusuario
curl -o /bin/renovarusuario https://raw.githubusercontent.com/devpow23/sc/main/files/renovarusuario 1> /dev/null 2> /dev/null
chmod +x /bin/renovarusuario
rm -rf /bin/vpspack
curl -o /bin/vpspack https://raw.githubusercontent.com/devpow23/sc/main/files/vpspack 1> /dev/null 2> /dev/null
chmod +x /bin/vpspack
rm -rf /bin/cargarmodulos
curl -o /bin/cargarmodulos https://raw.githubusercontent.com/devpow23/sc/main/files/cargarmodulos 1> /dev/null 2> /dev/null
chmod +x /bin/cargarmodulos
rm -rf /bin/speedtest.py
curl -o /bin/speedtest.py https://raw.githubusercontent.com/devpow23/sc/main/files/speedtest.py 1> /dev/null 2> /dev/null
chmod +x /bin/speedtest.py
rm -rf /bin/toolmaster
curl -o /bin/toolmaster https://raw.githubusercontent.com/devpow23/sc/main/files/toolmaster 1> /dev/null 2> /dev/null
chmod +x /bin/toolmaster
rm -rf /etc/VpsPackdir/pl.sh
curl -o /etc/VpsPackdir/pl.sh https://raw.githubusercontent.com/devpow23/sc/main/files/pl.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/pl.sh
rm -rf /etc/VpsPackdir/d.sh
curl -o /etc/VpsPackdir/d.sh https://raw.githubusercontent.com/devpow23/sc/main/files/d.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/d.sh
rm -rf /etc/VpsPackdir/initcheck.sh
curl -o /etc/VpsPackdir/d.sh https://raw.githubusercontent.com/devpow23/sc/main/files/initcheck.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/initcheck.sh
rm -rf /root/dropbear
curl -o /root/dropbear https://raw.githubusercontent.com/devpow23/sc/main/files/dropbear 1> /dev/null 2> /dev/null
rm /etc/VpsPackdir/ssl
curl -o /etc/VpsPackdir/ssl https://raw.githubusercontent.com/devpow23/sc/main/files/ssl 1> /dev/null 2> /dev/null
rm /etc/VpsPackdir/sslmulti
curl -o /etc/VpsPackdir/sslmulti https://raw.githubusercontent.com/devpow23/sc/main/files/sslmulti 1> /dev/null 2> /dev/null
rm /etc/VpsPackdir/stunnel
curl -o /etc/VpsPackdir/stunnel https://raw.githubusercontent.com/devpow23/sc/main/files/stunnel 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/shadowsocks.sh
curl -o /etc/VpsPackdir/shadowsocks.sh https://raw.githubusercontent.com/devpow23/sc/main/files/shadowsocks.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/shadowsocks.sh
rm -rf /bin/instaladores
curl -o /bin/instaladores https://raw.githubusercontent.com/devpow23/sc/main/files/instaladores 1> /dev/null 2> /dev/null
chmod +x /bin/instaladores
rm -rf /etc/VpsPackdir/proxyredir.py
curl -o /etc/VpsPackdir/proxyredir.py https://raw.githubusercontent.com/devpow23/sc/main/files/proxy.py 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/proxysocket.py
curl -o /etc/VpsPackdir/proxysocket.py https://raw.githubusercontent.com/devpow23/sc/main/files/proxysocket.py 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/confdropbear
curl -o /etc/VpsPackdir/confdropbear https://raw.githubusercontent.com/devpow23/sc/main/files/confdropbear 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/dropxbear
curl -o /etc/VpsPackdir/dropxbear https://raw.githubusercontent.com/devpow23/sc/main/files/dropxbear 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/dropxbear
rm -rf /etc/VpsPackdir/droplimit.sh
curl -o /etc/VpsPackdir/droplimit.sh https://raw.githubusercontent.com/devpow23/sc/main/files/droplimit.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/droplimit.sh
rm -rf /etc/VpsPackdir/badvpncron.sh
curl -o /etc/VpsPackdir/badvpncron.sh https://raw.githubusercontent.com/devpow23/sc/main/files/badvpncron.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/badvpncron.sh
rm -rf /etc/VpsPackdir/limpieza.sh
curl -o /etc/VpsPackdir/limpieza.sh https://raw.githubusercontent.com/devpow23/sc/main/files/limpieza.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/limpieza.sh
rm -rf /etc/VpsPackdir/enlinea.sh
curl -o /etc/VpsPackdir/enlinea.sh https://raw.githubusercontent.com/devpow23/sc/main/files/enlinea.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/enlinea.sh
rm -rf /etc/VpsPackdir/badudp.sh
curl -o /etc/VpsPackdir/badudp.sh https://raw.githubusercontent.com/devpow23/sc/main/files/badudp.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/badudp.sh
rm -rf /etc/VpsPackdir/badvpncheck.sh
curl -o /etc/VpsPackdir/badvpncheck.sh https://raw.githubusercontent.com/devpow23/sc/main/files/badvpncheck.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/badudp.sh
rm -rf /etc/VpsPackdir/proxycustom.py
curl -o /etc/VpsPackdir/proxycustom.py https://raw.githubusercontent.com/devpow23/sc/main/files/proxycustom.py 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/PGet.py
curl -o /etc/VpsPackdir/PGet.py https://raw.githubusercontent.com/devpow23/sc/main/files/PGet.py 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/Directo.py
curl -o /etc/VpsPackdir/Directo.py https://raw.githubusercontent.com/devpow23/sc/main/files/Directo.py 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/proxy101.py
curl -o /etc/VpsPackdir/proxy101.py https://raw.githubusercontent.com/devpow23/sc/main/files/proxy101.py 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/proxy301.py
curl -o /etc/VpsPackdir/proxy301.py https://raw.githubusercontent.com/devpow23/sc/main/files/proxy301.py 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/priv.sh
curl -o /etc/VpsPackdir/priv.sh https://raw.githubusercontent.com/devpow23/sc/main/files/priv.sh 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/pub.sh
curl -o /etc/VpsPackdir/pub.sh https://raw.githubusercontent.com/devpow23/sc/main/files/pub.sh 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/badcron.sh
curl -o /etc/VpsPackdir/badcron.sh https://raw.githubusercontent.com/devpow23/sc/main/files/badcron.sh 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/ws-epro
wget 'https://docs.google.com/uc?export=download&id=1IbwfNpKpa1JzvXsDT-WgNpp5nWrklisG' -O /etc/VpsPackdir/ws-epro 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/ws-epro
rm -rf /bin/payloadssl
curl -o /bin/payloadssl https://raw.githubusercontent.com/devpow23/sc/main/files/payloadssl 1> /dev/null 2> /dev/null
chmod +x /bin/payloadssl
rm -rf /bin/v2rayadmin
curl -o /bin/v2rayadmin https://raw.githubusercontent.com/devpow23/sc/main/files/v2rayadmin 1> /dev/null 2> /dev/null
chmod +x /bin/v2rayadmin
rm -rf /bin/slowdnsins
curl -o /etc/VpsPackdir/slowdnsins https://raw.githubusercontent.com/devpow23/sc/main/files/slowdnsins 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/slowdnsins
rm /etc/VpsPackdir/socks/s.zip &>/dev/null
curl -o /etc/VpsPackdir/socks/s.zip https://raw.githubusercontent.com/devpow23/sc/main/files/s.zip 1> /dev/null 2> /dev/null
cd /etc/VpsPackdir/socks/
unzip -o s.zip 
rm /etc/VpsPackdir/socks/s.zip &>/dev/null
cd /root &>/dev/null
if grep vpspack /etc/ssh/sshd_config; then
   echo "vpspack found OK"
else
   cp /etc/VpsPackdir/sshconf /etc/ssh/sshd_config;
   service ssh restart
   echo "Configurado" 
fi
if [ -f /etc/banner ];
then
echo "Banner Detectado"
else
curl -o /etc/banner https://raw.githubusercontent.com/devpow23/sc/main/files/banner 1> /dev/null 2> /dev/null
fi
chmod +x /root/dropbear
}
fun_bar 'preparar'
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m Instalando Paquetes basicos\033[1;33m"
apt-get -y install nano 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "nano"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "nano"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → NANO \033[1;31m  ─────────────── /// ─── $status "
apt-get -y install net-tools 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "net-tools"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "net-tools"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → NET-TOOLS \033[1;31m ─────────── /// ─── $status "
apt-get -y install unzip 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "unzip"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "unzip"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → UNZIP \033[1;31m ─────────────── /// ─── $status "
apt-get -y install htop 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "htop"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "htop"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → HTOP \033[1;31m ──────────────── /// ─── $status "
apt-get -y install figlet 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "figlet"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "figlet"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → FIGLET \033[1;31m ────────────── /// ─── $status "
apt-get -y install git 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "git"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "git"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → GIT \033[1;31m ───────────────── /// ─── $status "
apt-get -y install build-essential libpq-dev libffi-dev zlib1g-dev 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "libffi-dev"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "libffi-dev"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → LIBFFI \033[1;31m ────────────── /// ─── $status "
apt-get -y install screen 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "screen"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "screen"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → SCREEN \033[1;31m ────────────── /// ─── $status "
apt-get -y install python3-pip 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "python3-pip"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "python3-pip"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → PYTHON3-PIP \033[1;31m ───────── /// ─── $status "
apt-get -y install nload 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "nload"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "nload"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → NLOAD \033[1;31m ─────────────── /// ─── $status "
apt-get -y install dos2unix 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "dos2unix"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "dos2unix"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → DOS2UNIX \033[1;31m ──────────── /// ─── $status "
apt-get -y install lsof 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "lsof"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "lsof"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → LSOF \033[1;31m ──────────────── /// ─── $status "
apt-get -y install speedtest-cli 1> /dev/null 2> /dev/null
pip install speedtest-cli 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "speedtest-cli"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "speedtest-cli"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → SPEEDTEST \033[1;31m ─────────── /// ─── $status "
apt-get -y install openssl libssl-dev pkg-config 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "libssl-dev"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "libssl-dev"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → LIBSSL \033[1;31m ────────────── /// ─── $status "
apt-get install -y neofetch 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "neofetch"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "neofetch"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → NEOFETCH \033[1;31m ──────────── /// ─── $status "
apt-get -y install vnstat 1> /dev/null 2> /dev/null
[[ $(dpkg --get-selections|grep -w "vnstat"|head -1) ]] || status=`echo -e "\033[1;33mFallo en instalacion"` &>/dev/null
[[ $(dpkg --get-selections|grep -w "vnstat"|head -1) ]] && status=`echo -e "\033[1;32mInstalado"` &>/dev/null
echo -e "\033[1;33m → VNSTAT \033[1;31m  ───────────── /// ─── $status "
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m Instalacion de Paquetes Finalizada\033[1;33m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m Presione Cualquier Tecla\033[1;33m"
read -p " "
clear
if cat /root/.bashrc | grep vpspack; then
echo -e ":)" &>/dev/null
clear
else
echo 'export PATH=$PATH:/usr/sbin' >> ~/.bashrc
echo "clear" >> .bashrc 
echo 'cat /etc/VpsPackdir/logo' >> .bashrc
echo 'DATE=$(date +"%d-%m-%y")' >> .bashrc 
echo 'TIME=$(date +"%T")' >> .bashrc 
echo 'IPS=$(cat /etc/VpsPackdir/ip)' >> .bashrc
echo 'echo -e ""' >> .bashrc 
echo 'echo -e "Nombre del Servidor : $HOSTNAME"' >> .bashrc
echo 'echo -e "IP del Servidor : $IPS"' >> .bashrc 
echo 'echo -e "Fecha del Servidor : $DATE"' >> .bashrc 
echo 'echo -e "Hora del Servidor : $TIME"' >> .bashrc 
echo 'echo -e ""' >> .bashrc 
echo 'echo -e "Bienvenido!"' >> .bashrc 
echo 'echo -e "Teclee vpspack para ver el menu."' >> .bashrc
echo 'echo -e ""' >> .bashrc 
clear
fi
clear
echo -e "\033[1;32m────────────────────\033[1;32m /// \033[1;32m─────────────────────\033[1;33m"
rm /etc/VpsPackdir/ip 1> /dev/null 2> /dev/null
touch /etc/VpsPackdir/ip 1> /dev/null 2> /dev/null
echo "$IP" > /etc/VpsPackdir/ip 
echo -e "\033[1;32m "
echo -e "\033[1;32m─── /// ─── \033[1;31mInstalacion Finalizada\033[1;32m ─── /// ───\033[1;30m"
echo -e "\n\033[1;32m IP Publica \033[1;31m $IP "
echo -e "\n\033[1;32m vpspack     \033[1;31mMENU DE OPCIONES"
echo -e "$fecha" >> /etc/VpsPackdir/fecha
echo -e "\033[1;32m────────────────────\033[1;32m /// \033[1;32m─────────────────────\033[1;33m"
cd /root
rm ins 1> /dev/null 2> /dev/null
history -c 1> /dev/null 2> /dev/null
vpspack
